namespace PenomyAPI.App.FeatArt17;

public enum Art17ResponseAppCode
{
    SUCCESS = 0,

    CURRENT_CREATOR_IS_NOT_AUTHORIZED,

    DATABASE_ERROR,

    FILE_SERVICE_ERROR,

    INVALID_JSON_SCHEMA_FROM_INPUT_CATEGORIES,

    INVALID_FILE_EXTENSION,

    INVALID_FILE_FORMAT,

    FILE_SIZE_IS_EXCEED_THE_LIMIT,
}
